routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RoleAccessController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    // MENU
    Route::resource('menu', MenuController::class);
    Route::post('/menuup', [MenuController::class, 'up'])->name('menu.up');
    Route::post('/menudown', [MenuController::class, 'down'])->name('menu.down');

    // ROLE
    Route::resource('role', RoleController::class);
    
    // ROLE ACCESS
    Route::resource('roleaccess', RoleAccessController::class);
    Route::get('/role/detail-role/{id}', [RoleAccessController::class, 'detailRole']); 
    Route::get('/role/detail-role/create/{id}', [RoleAccessController::class, 'create']); 
    Route::post('/role/detail-role/store/{id}', [RoleAccessController::class, 'store']); 
    Route::get('/role/detail-role/edit/{id}', [RoleAccessController::class, 'edit']); 
    Route::put('/role/detail-role/update/{id}', [RoleAccessController::class, 'update']); 
    Route::delete('/role/detail-role/destroy/{id}', [RoleAccessController::class, 'destroy']); 

    // USER
    Route::resource('user', UserController::class);
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\Rrole;

class RoleController extends Controller
{
    protected $route_name = 'role';
    protected $route_detail = 'roleaccess';

    public function __construct(Rrole $role)
    {
        $this->middleware('auth');
        $this->role = $role;
        //get parmission menu where kode menu and status true
        $this->menu = getPermissionMenu('KDROLE');
        $var = array(
            'title' => 'Role',
            'route_name' => 'role'
        );
        $breadcrumb = [
            [
                "route" => 'home',
                "name" => "Home"
            ],
            [
                "route" => 'role',
                "name" => "Role"
            ]
        ];
        View::share(['var'=> $var, 'permissionMenu' => $this->menu, 'breadcrumb' => $breadcrumb]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = $this->role->latest()->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('role_name',function($data){
                    if (empty($data->role_name)) {
                        $role_name = "<p class='text-danger'>Tidak ada Nama Role</p>";
                    } else {
                        $role_name = $data->role_name;
                    }
                    return $role_name;
                })

                ->addColumn('role_code',function($data){
                    if (empty($data->role_code)) {
                        $role_code = "<p class='text-danger'>Tidak ada Nama Role</p>";
                    } else {
                        $role_code = $data->role_code;
                    }
                    return $role_code;
                })
                
                ->addColumn('role_status',function($data){
                    if ($data->role_status == 1) {
                        $role_status = "<div class='badge badge-success'>Active</div>";
                    } else {
                        $role_status = "<div class='badge badge-danger'>Inactive</div>";
                    }
                    return $role_status;
                })
                
                ->addColumn('action', function($data){
                    $btn = '
                        <a href="'.url($this->route_name.'/detail-role/'.$data->idr_role).'" class="btn btn-icon btn-info my-1" title="Edit"><i class="fas fa-search"></i></a>
                        <a href="'.route($this->route_name.'.edit',$data->idr_role).'" class="btn btn-icon btn-warning my-1" title="Edit"><i class="fas fa-edit"></i></a>
                        <a href="'.route($this->route_name.'.destroy', $data->idr_role).'" data-id="" class="btn btn-icon btn-danger btn-delete-on-table" title="Delete"><i class="fas fa-trash"></i></a>
                        ';
                    return $btn;
                })
                ->rawColumns(['action','role_status','role_name','role_code'])
                ->make(true);
        }

        return view($this->route_name.'.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $action = route($this->route_name.".store");
        return view($this->route_name.'.form', compact('action'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'role_name' => 'required',
            'role_code' => 'required',
            'role_status' => 'required',
        ],[
            'required'  => 'Kolom :attribute tidak boleh kosong.',
            'unique'    => ':attribute sudah digunakan'
        ]);
        
        $role = new $this->role;
        $role->role_name = $request->role_name;
        $role->role_code = $request->role_code;
        $role->role_status = $request->role_status;
        $role->created_by = Auth::user()->name;
        $role->created_at = new \DateTime;

        $role->save();
        return redirect($this->route_name)->with(['success' => 'Data berhasil disimpan!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $action = route($this->route_name.'.update',$id);
        $data = $this->role->findOrFail($id);
        return view($this->route_name.'.form', compact('data', 'action'));       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'role_name' => 'required',
            'role_code' => 'required',
            'role_status' => 'required',
        ],[
            'required'  => 'Kolom :attribute tidak boleh kosong.',
            'unique'    => ':attribute sudah digunakan'
        ]);
        
        $role = $this->role->findOrFail($id);

        $role->role_name = $request->role_name;
        $role->role_code = $request->role_code;
        $role->role_status = $request->role_status;
        $role->updated_by = Auth::user()->name;
        $role->updated_at = new \DateTime;

        $role->save();
        return redirect($this->route_name)->with(['success' => 'Data berhasil diperbarui!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = $this->role->findOrFail($id);
        if($delete->delete()){
            return response()->json(['code' => '200', 'message' => 'Data berhasil dihapus']);
        }else{
            return response()->json(['code' => '400', 'message' => 'Data gagal dihapus']);
        }
    }
}

resources/views/role/form.blade.php
<!-- Main Layout -->
@extends('layouts.main')

@section('content')
<section class="section">
    <div class="section-body">
        <div class="card">
            <form method="POST" action="{{ $action }}">
                @csrf
                @if (isset($data))
                    @method('PUT')
                @endif
                
                <div class="card-header">
                    <h4>
                        Form {{ isset($data)?'Ubah':'Tambah' }} {{ $var['title'] }}
                    </h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Nama Role</label>
                        <input type="text" name="role_name" class="form-control @error('role_name') is-invalid @enderror" value="{{ isset($data)?$data->role_name:'' }}" placeholder="Contoh: Perwakilan">
                        @error('role_name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Kode Role</label>
                        <input type="text" name="role_code" value="{{ isset($data)?$data->role_code:'' }}" class="form-control @error('role_code') is-invalid @enderror" placeholder="Contoh: KDPERWAKILAN">
                        @error('role_code')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Status</label>
                        <div class="row">
                            <div class="selectgroup w-100 col-md-4">
                                <label class="selectgroup-item">
                                    <input type="radio" name="role_status" id="status_aktif" value="1" class="selectgroup-input" @if (isset($data)) @if ($data->role_status == 1) checked @endif @endif>
                                    <span class="selectgroup-button">Active</span>
                                </label>
                                <label class="selectgroup-item">
                                    <input type="radio" name="role_status" id="status_tidakaktif" value="0" class="selectgroup-input" @if (isset($data)) @if ($data->role_status == 0) checked @endif @endif>
                                    <span class="selectgroup-button">Inactive</span>
                                </label>
                            </div>
                        </div>
                        @error('role_status')
                            <p style="width: 100%;font-size: 80%;color: #e3342f;">{{ $message }}</p>
                        @enderror
                    </div>
                    
                </div>
                <div class="card-footer text-right">
                    <a href="{{ route('role.index') }}" class="btn btn-info icon-left"><i class="fas fa-arrow-left mr-1"></i>Back</a>
                    <button class="btn btn-primary"><i class="far fa-save mr-1"></i>Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
@endsection

resources/views/role/index.blade.php
<!-- Main Layout -->
@extends('layouts.main')
<!-- Additional css Content -->
@section('style')
    @include('partials.css');
@endsection

@section('content')
<style>
    table td, table tr th {
        vertical-align: middle !important;
    }
</style>
<!-- Main Content -->
<section class="section">
    @include('partials.section-header')
    
    <div class="section-body">
        <h2 class="section-title">{{ $var['title'] }}</h2>
        <p class="section-lead">Components that can be used to make something bigger than the header.</p>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{ $var['title'] }} DataTables</h4>
                        <div style="display: block; float: right; margin-left: auto;">
                            <a href="{{ route($var['route_name'].'.create') }}" class="btn btn-icon icon-left btn-primary"><i class="fas fa-plus"></i> Add</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-responsive-sm" id="table-1" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Role</th>
                                    <th>Code</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('script')
{{-- Additional JS --}}
@include('partials.js')

<script>
 var table = $("#table-1").dataTable({
    processing: true,
    serverSide: true,
    ajax: "{{ route($var['route_name'].'.index') }}",
    columns: [
        {data: 'DT_RowIndex', className : "text-center"},
        {data: 'role_name'},
        {data: 'role_code'},
        {data: 'role_status', className : "text-center"},
        {data: 'action', className : "text-center", orderable: false, searchable: false},
    ]
});
</script>
@endsection