routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RoleAccessController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    // MENU
    Route::resource('menu', MenuController::class);
    Route::post('/menuup', [MenuController::class, 'up'])->name('menu.up');
    Route::post('/menudown', [MenuController::class, 'down'])->name('menu.down');

    // ROLE
    Route::resource('role', RoleController::class);
    
    // ROLE ACCESS
    Route::resource('roleaccess', RoleAccessController::class);
    Route::get('/role/detail-role/{id}', [RoleAccessController::class, 'detailRole']); 
    Route::get('/role/detail-role/create/{id}', [RoleAccessController::class, 'create']); 
    Route::post('/role/detail-role/store/{id}', [RoleAccessController::class, 'store']); 
    Route::get('/role/detail-role/edit/{id}', [RoleAccessController::class, 'edit']); 
    Route::put('/role/detail-role/update/{id}', [RoleAccessController::class, 'update']); 
    Route::delete('/role/detail-role/destroy/{id}', [RoleAccessController::class, 'destroy']); 

    // USER
    Route::resource('user', UserController::class);
});

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;
use App\Models\Rmenu;
use Illuminate\Support\Facades\Auth;
use DB;

class MenuController extends Controller
{
    /**
    * Create a new controller instance.
    *
    * @return void
    */
    
    public function __construct(Rmenu $rmenu)
    {
        $this->middleware('auth');
        //array permission menu
        $this->position_menu = ['SIDE','TOP','CONTENT','TITLE','SIDEPARENT','SIDECHILD'];
        //get parmission menu where kode menu and status true
        $this->menu = getPermissionMenu('MNU');
        //declare breadcrumb link
        $breadcrumb = [
            [
                "route" => 'home',
                "name" => "Home"
            ],
            [
                "route" => 'menu',
                "name" => "Menu"
            ]
        ];
        //declare array
        $var = array(
            'title' => 'Menu',
            'route_name' => 'menu'
        );
        View::share(['var' => $var, 'permissionMenu' => $this->menu, 'breadcrumb' => $breadcrumb]);
    }

    /**
    * Show the application dashboard.
    *
    * @return \Illuminate\Contracts\Support\Renderable
    */

    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Rmenu::orderBy('order_menu', 'ASC')->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('parent',function($data){
                    if (empty($data->idr_parent)) {
                        $parent = "<p class='text-danger'>Tidak ada Parent</p>";
                    } else {
                        $parent = $data->idr_parent;
                    }
                    return $parent;
                })
                ->addColumn('route',function($data){
                    if (empty($data->controller_menu)) {
                        $route = "<p class='text-danger'>Tidak ada Route</p>";
                    } else {
                        $route = $data->controller_menu;
                    }
                    return $route;
                })
                ->addColumn('icon',function($data){
                    if (empty($data->icon_menu)) {
                        $icon = "<p class='text-danger'>Tidak ada Icon</p>";
                    } else {
                        $icon = $data->icon_menu;
                    }
                    return $icon;
                })
                ->addColumn('status',function($data){
                    if ($data->status_menu == 1) {
                        $status = "<div class='badge badge-success'>Active</div>";
                    } else {
                        $status = "<div class='badge badge-danger'>Inactive</div>";
                    }
                    return $status;
                })
                ->addColumn('action', function($data){
                    $up = '<a href="'.route('menu.up').'" class="btn btn-icon btn-light mr-1 mb-1 btn-update-on-table" title="Up Menu"><i class="fas fa-arrow-up"></i></a>';
                    $down = '<a href="'.route('menu.down').'" class="btn btn-icon btn-light mr-1 mb-1 btn-update-on-table" title="Down Menu"><i class="fas fa-arrow-down"></i></a>';
                    $edit = '<a href="'.route('menu.edit',$data->idr_menu).'" class="btn btn-icon btn-warning mr-1 mb-1" title="Edit"><i class="fas fa-edit"></i></a>';
                    $delete = '<a href="'.route('menu.destroy', $data->idr_menu).'" data-id="" class="btn btn-icon btn-danger mr-1 mb-1 btn-delete-on-table" title="Delete"><i class="fas fa-trash"></i></a>';
                    if($this->menu['edit_access'] == '0' && $this->menu['delete_access'] == '0'){                            
                        $btn = $up.$down;
                    //permission edit true, permission delete false
                    }else if($this->menu['edit_access'] == '1' && $this->menu['delete_access'] == '0'){
                        $btn = $up.$down.$edit;
                    //permission edit true, permission delete false
                    }else if($this->menu['edit_access'] == '0' && $this->menu['delete_access'] == '1'){
                        $btn = $up.$down.$delete;
                    //permission edit true, permission delete true
                    }else if($this->menu['edit_access'] == '1' && $this->menu['delete_access'] == '1'){
                        $btn = $up.$down.$edit.$delete;
                    }
                    return $btn;
                })
                ->rawColumns(['action','status','read','add','edit','delete','parent','route','icon'])
                ->make(true);
        }
        return view('menu.index');
    }

    public function create(){
        $action = route('menu.store');
        $menu_parent = $rmenu::where('position_menu', 'SIDEPARENT')->get();

        return view('menu.add')->with(['action' => $action, 'position' => $this->position_menu, 'menu' => $menu_parent]);
    }

    public function store(Request $request){
        $validated = $request->validate([
            'name_menu' => 'required|unique:r_menu',
            'controller_menu' => 'required',
            'kode_menu' => 'required',
            'position_menu' => 'required',
        ],[
            'required'  => 'Kolom :attribute tidak boleh kosong.',
            'unique'    => ':attribute sudah digunakan'
        ]);

        //get last order number
        $order_number = Rmenu::orderBy('order_menu', 'DESC')->first();

        $save = new Rmenu;
        $save->name_menu = $request->name_menu;
        $save->controller_menu = $request->controller_menu;
        $save->kode_menu = $request->kode_menu;
        $save->position_menu = $request->position_menu;
        $save->idr_parent = $request->idr_parent;
        $save->icon_menu = $request->icon_menu;
        $save->status_menu = $request->status;
        $save->order_menu = $order_number->order_menu+1;
        $save->created_by = Auth::user()->name;
        $save->save();

        return redirect('menu')->with(['success' => 'Data berhasil disimpan!']);
    }

    public function edit($id)
    {
        $data = Rmenu::findOrFail($id);
        $action = route('menu.update',$id);
        $menu_parent = $rmenu::where('position_menu', 'SIDEPARENT')->get();
        
        return view('menu.add', compact('data','action'))->with(['position' => $this->position_menu, 'menu' => $menu_parent]);
    }

    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'name_menu' => 'required',
            'controller_menu' => 'required',
            'kode_menu' => 'required',
            'position_menu' => 'required',
        ],[
            'required'  => 'Kolom :attribute tidak boleh kosong.',
            'unique'    => ':attribute sudah digunakan'
        ]);

        $update = Rmenu::findOrFail($id);
        $update->name_menu = $request->name_menu;
        $update->controller_menu = $request->controller_menu;
        $update->kode_menu = $request->kode_menu;
        $update->position_menu = $request->position_menu;
        $update->idr_parent = $request->idr_parent;
        $update->icon_menu = $request->icon_menu;
        $update->status_menu = $request->status;
        $update->updated_by = Auth::user()->name;
        $update->save();

        return redirect('menu')->with(['success' => 'Data berhasil diperbarui!']);
    }

    public function destroy($id){
        $delete = Rmenu::findOrFail($id);
        if($delete->delete()){
            return response()->json(['code' => '200', 'message' => 'Data berhasil dihapus']);
        }else{
            return response()->json(['code' => '400', 'message' => 'Data gagal dihapus']);
        }
    }

    public function up(Request $request){
        $id = $request->post('id');
        $value = $request->post('value');
        
        if($request->post('value') == 1){
            return response()->json(['code' => '400', 'message' => 'Urutan menu sudah pertama']);
        }

        DB::beginTransaction();
        try {
            //mendapatkan row menu sebelumnya
            $menu_prev = Rmenu::where('order_menu', $value-1)->first();
            $menu_prev->order_menu = $value;
            $menu_prev->save();

            //mendapatkan row menu selanjutnya
            $menu_next = Rmenu::findOrFail($id);
            $menu_next->order_menu = $value-1;
            $menu_next->save();
            DB::commit();
            return response()->json(['code' => '200', 'message' => 'Data berhasil diperbarui</br>Silahkan Refresh page']);
        } catch (Exception $e) {
            DB::rollBack();
            return response()->json(['code' => '400', 'message' => 'Data gagal diperbarui']);
        }
    }

    public function down(Request $request){
        $id = $request->post('id');
        $value = $request->post('value');

        DB::beginTransaction();
        try {
            //mendapatkan row menu sebelumnya
            $menu_prev = Rmenu::where('order_menu', $value+1)->first();
            $menu_prev->order_menu = $value;
            $menu_prev->save();

            //mendapatkan row menu selanjutnya
            $menu_next = Rmenu::findOrFail($id);
            $menu_next->order_menu = $value+1;
            $menu_next->save();
            DB::commit();
            return response()->json(['code' => '200', 'message' => 'Data berhasil diperbarui</br>Silahkan Refresh page']);
        } catch (Exception $e) {
            DB::rollBack();
            return response()->json(['code' => '400', 'message' => 'Data gagal diperbarui']);
        }
    }
}

resources/views/menu/add.blade.php
<!-- Main Layout -->
@extends('layouts.main')

@section('content')
<section class="section">
    <div class="section-body">
        <div class="card">
            <form method="POST" action="{{ $action }}">
                @csrf
                @if (isset($data))
                    @method('PUT')
                @endif
                <div class="card-header">
                    <h4>Form {{ isset($data)?'Ubah':'Tambah' }} {{ $var['title'] }}</h4>
                </div>
                <div class="card-body">
                    <div>
                        <div class="form-group">
                            <label>Posisi Menu</label>
                            <select name="position_menu" class="form-control select2 @error('position_menu') is-invalid @enderror" aria-required="true" aria-invalid="false">
                              <option value="">-- Pilih Data --</option>
                              @foreach ($position as $rposition)
                                  <option value="{{ $rposition }}" {{ old('position_menu', isset($data) ? $data->position_menu : '') == $rposition ? 'selected' : '' }}>{{ $rposition }}</option>
                              @endforeach
                            </select>
                          </div>
                        @error('position_menu')
                            <p style="width: 100%;margin-top: 0.25rem;font-size: 80%;color: #e3342f;">{{ $message }}</p>
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div>
                        <div class="form-group">
                            <label>Parent Menu</label>
                            <select name="idr_parent" class="form-control select2 @error('idr_parent') is-invalid @enderror" aria-required="true" aria-invalid="false">
                              <option value="">-- Pilih Data --</option>
                              @foreach ($menu as $rmenu)
                                  <option value="{{ $rmenu->idr_menu }}" {{ old('idr_parent', isset($data) ? $data->idr_parent : '') == $rmenu->idr_menu ? 'selected' : '' }}>{{ $rmenu->name_menu }}</option>
                              @endforeach
                            </select>
                          </div>
                        @error('idr_parent')
                            <p style="width: 100%;margin-top: 0.25rem;font-size: 80%;color: #e3342f;">{{ $message }}</p>
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Nama Menu</label>
                        <input type="text" name="name_menu" class="form-control @error('name_menu') is-invalid @enderror" placeholder="Contoh: Menu 1" value="{{ old('name_menu', isset($data) ? $data->name_menu : '') }}">
                        @error('name_menu')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Route Menu</label>
                        <input type="text" name="controller_menu" class="form-control @error('controller_menu') is-invalid @enderror" placeholder="Contoh : menu1" value="{{ old('controller_menu', isset($data) ? $data->controller_menu : '') }}">
                        @error('controller_menu')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Kode Menu</label>
                        <input type="text" name="kode_menu" class="form-control @error('kode_menu') is-invalid @enderror" placeholder="Contoh : MNU1" value="{{ old('kode_menu', isset($data) ? $data->kode_menu : '') }}">
                        @error('kode_menu')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Icon Menu</label>
                        <input type="text" name="icon_menu" class="form-control" placeholder="Contoh : fa-home" value="{{ isset($data) ? $data->icon_menu : old('icon_menu') }}">
                    </div>
                    <div class="form-group">
                        <label>Status</label>
                        <div class="row">
                            <div class="selectgroup w-100 col-md-6">
                                <label class="selectgroup-item">
                                    <input type="radio" name="status" id="status_aktif" value="1" class="selectgroup-input" {{ old('status', isset($data) ? $data->status_menu : '') == 1 ? 'checked' : '' }}>
                                    <span class="selectgroup-button">Active</span>
                                </label>
                                <label class="selectgroup-item">
                                    <input type="radio" name="status" id="status_tidakaktif" value="0" class="selectgroup-input" {{ old('status', isset($data) ? $data->status_menu : '') == 0 ? 'checked' : '' }}>
                                    <span class="selectgroup-button">Inactive</span>
                                </label>
                            </div>
                        </div>
                        <div class="invalid-feedback">
                            Good job!
                        </div>
                </div>
                <div class="card-footer text-right">
                    <a href="{{ route('menu.index') }}" class="btn btn-info icon-left"><i class="fas fa-arrow-left mr-1"></i>Back</a>
                    <button class="btn btn-primary"><i class="far fa-save mr-1"></i>Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
@endsection
@section('script')
@include('partials.js_form')
@endsection

resources/views/menu/index.blade.php
<!-- Main Layout -->
@extends('layouts.main')
<!-- Additional css Content -->
@section('style')
    @include('partials.css');
@endsection

@section('content')
<style>
    table td, table tr th {
        vertical-align: middle !important;
    }
</style>
<!-- Main Content -->
<section class="section">
    @include('partials.section-header')

    <div class="section-body">
        <h2 class="section-title">{{ $var['title'] }}</h2>
        <p class="section-lead">Components that can be used to make something bigger than the header.</p>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Menu Tables</h4>
                        {{-- jika permission create true --}}
                        @if ($permissionMenu['add_access'] == '1')
                            <div style="display: block; float: right; margin-left: auto;">
                                <a href="{{ route('menu.create') }}" class="btn btn-icon icon-left btn-primary"><i class="fas fa-plus"></i> Add</a>
                            </div>
                        @endif
                        {{-- end of jika permission create true --}}
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-responsive-sm display" id="table-1" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Name</th>
                                    <th>Position</th>
                                    <th>Parent</th>
                                    <th>Route</th>
                                    <th>Icon</th>
                                    <th>Order</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('script')
{{-- Additional JS --}}
@include('partials.js')

<script>
var table;
table = $("#table-1").dataTable({
    processing: true,
    serverSide: true,
    ajax: "{{ route('menu.index') }}",
    columns: [
        {data: 'DT_RowIndex', className : "text-center"},
        {data: 'name_menu'},
        {data: 'position_menu'},
        {data: 'parent'},
        {data: 'route'},
        {data: 'icon'},
        {data: 'order_menu', className : "text-center"},
        {data: 'status', className : "text-center"},
        {data: 'action', className : "text-center", orderable: false, searchable: false},
    ]
});

$("tbody").on("click",".btn-update-on-table",function(e){
    e.preventDefault();
    var thisUrl = $(this).attr("href");
    var data = $("#table-1").DataTable().row($(this).parents('tr')).data();

    var array = {
        'id' : data.idr_menu,
        'value' : data.order_menu
    }
    console.log(array);

    Swal.fire({
        title: 'Tunggu sesaat...',
        text: 'Aplikasi sedang melakukan proses data',
        closeOnClickOutside: false,
        allowOutsideClick: false
    });
    Swal.showLoading();
    $.ajax({
        url : thisUrl,
        type : "POST",
        dataType : "json",
        data: array,
        success : function(result){
            if(result.code == 200){
                swal.fire("Success", result.message,"success");
            //   table.ajax.reload( null, false );
            $("#table-1").DataTable().ajax.reload();
            }else if(result.code == 400){
                swal.fire("Oops!", result.message,"error");
            }else{
                swal.fire("Oops!","Gagal memproses data, silahkan coba lagi", 'error');
            }
        },
        error : function()
        {
            swal.fire("Oops!","Gagal memproses data, silahkan coba lagi", 'error');
        }
    })
});
</script>
@endsection